# https://stratis.atlassian.net/wiki/spaces/SEC/pages/2580119635/Fortify
name: fortify-on-demand 
schedules:
  - cron: "0 0 * * 0"
    displayName: Every Sunday    
    branches:
    include:
      - main
    always: true
trigger: none 
pr: none 

pool: 
name: dotnet-pool

parameters: 
  - name: releaseId
    displayName: Fortify on Demand Release ID    
    type: number    
    default: 832709
  - name: buildType
    displayName: Fortify on Demand Build Type
    type: string
    default: "none"
  - name: sast
    displayName: Run SAST Scan
    type: boolean
    default: true
jobs:
  - job: SAST
    pool: dotnet-pool
    condition: eq('${{ parameters.sast }}', true)
    steps:
      - task: FortifyOnDemandStatic@8
        inputs:
          FortifyProjects: "$(Build.SourcesDirectory)"
          FodConnection: "Fortify-Connection"
          ReleaseOptions: "0"
          ReleaseId: "${{ parameters.releaseId }}"
          EntitlementSelection: "1"
          EntitlementPreference: "1"
          OverrideScanSettings: "2"
          InProgressScanActionType: "2"
          RemediationScanPreference: "0"
          BuildType: "${{ parameters.buildType }}"
          PolicyFailAction: "0"
      - task: DeleteFiles@1
        displayName: "Delete files from $(Agent.BuildDirectory)"
        inputs:
          SourceFolder: "$(Agent.BuildDirectory)"
          Contents: |
            /a/source.zip
        condition: succeededOrFailed()
          
